eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    perfer-in-address: true
    metadata-map:
      host-mark: running-host

server:
  port: 8763

spring:
  application:
    name: joke-server

logging:
  level:
    com.deepflow.joke.controller: debug
