eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    perfer-in-address: true

server:
  port: 8766
  servlet:
    context-path: /uaa      # web 的基路径

spring:
  application:
    name: uaa-server