spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     # 开启基于服务发现的路由规则
          lower-case-service-id: true   # 开启小写的 serviceId 进行基于服务路由的转发
      routes:
      - id: comment-server
        uri: lb://comment-server
        predicates:
        - Path=/comment-server # 路由集群内其他服务,url需要用[lb://]+[serviceId]
      # Host 路由断言工厂
      - id: host_route
        uri: https://blog.csdn.net/zjhcxdj/category_9771365.html
        predicates:
        - Host=**.csdn.**:15000 # 请求域名中携带 csdn,则转发
      # Query 路由断言工厂
      - id: query_route
        uri: https://blog.csdn.net/zjhcxdj/article/details/106992956
        predicates:
        - Query=username,zzz # 请求参数含有username,且值为zzz
      # Header 路由断言工厂
      - id: header_route
        uri: https://blog.csdn.net/zjhcxdj/article/details/105631321
        predicates:
        - Header=request, \d+ # 如果请求头含有request,且为数字,则转发
    loadbalancer:
      retry:
        enabled: true # 内部已默认开启负载均衡

eureka:
  client:
    service-url:
      defaultZone: http://localhost:15002/eureka/  # 指定注册中心地址, 以便使用服务发现功能
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    perfer-in-address: true

server:
  port: 15000

ribbon:
  ConnectionTimeout: 3000
  ReadTimeout: 10000
  MaxAutoRetries: 10 # 对第一次请求的服务重试的次数
  MaxAutoRetriesNexServer: 10 #要重试的下一个服务的最大数量(不包括第一个服务)
  OkToRetryOnAllOperations: true
#  eureka:
#    enabled: true
management:
  endpoints:
    health:
      enabled: true
    gateway:
      enabled: true
    web:
      exposure:
        include: "*" # 暴露所有端点, 默认是 info, health

logging:
  level:
    org.springframework.cloud.gateway: debug