eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    perfer-in-address: true

server:
  port: 8765

spring:
  application:
    name: gateway-zuul

zuul:
  routes:
#    joke-server:
#      path: /jokes-server/**
#      serviceId: jake-server
#    comment-server:
#      path: /comment-server/**
#      serciceId: comment-server
    joke-server:
    comment-server:
    uaa-server:

security:
  basic: false
  oauth2:
    client:
      access-token-uri: http://localhost:8766/uaa/oauth/token     # 令牌端点
      user-authorization-uri: http://localhost:8766/uaa/oauth/authorize   # 授权端点
      client-id: uaa-server         # OAuth2 客户端ID
      client-secret: secret         # OAuth2 客户端密钥
    resource:
      jwt:
        key-value: springcloud123                                     # 使用对称加密方式, 默认算法为HS256