eureka:
  client:
    server-url:
      defaultZone: http://localhost:15002/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    perfer-in-address: true

server:
  port: 15000

spring:
  application:
    name: gateway-zuul
  cloud:
    loadbalancer:
      retry:
        enabled: true # 内部已默认开启负载均衡

zuul:
  routes:
#    joke-server:
#      path: /jokes-server/**
#      serviceId: jake-server
#    comment-server:
#      path: /comment-server/**
#      serciceId: comment-server
    joke-server:
    comment-server:
    uaa-server:
  # 开启重试功能
  retryable: true

ribbon:
  ConnectionTimeout: 3000
  ReadTimeout: 10000
  MaxAutoRetries: 10 # 对第一次请求的服务重试的次数
  MaxAutoRetriesNexServer: 10 #要重试的下一个服务的最大数量(不包括第一个服务)
  OkToRetryOnAllOperations: true
#  eureka:
#    enabled: true

# TODO security does not work
#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:7777/uaa/oauth/token                 # 令牌端点
#      user-authorization-uri: http://localhost:7777/uaa/oauth/authorize      # 授权端点
#      client-id: zuul_server                                                  # OAuth2 客户端ID
#      client-secret: secret                                                   # OAuth2 客户端密钥
#    resource:
#      jwt:
#        key-value: springcloud123                                             # 使用对称加密方式, 默认算法为HS256