eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    perfer-in-address: true

server:
  port: 8765

spring:
  application:
    name: gateway-zuul

zuul:
  routes:
    joke-server:
      path: /jokes-server/**
      serviceId: jake-server
    comment-server:
      path: /comment-server/**
      serciceId: comment-server