eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    perfer-in-address: true

server:
  port: 15004

spring:
  application:
    name: eureka-client